title: Careless Prescriptions
email: reginafcompton@gmail.com
description: >
  A website that explores and confronts the overprescribing of anti-psychotic drugs and the risks of drug treatment in mental health care. Organized by Glenn and Mary Compton.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ""
github_username: ""

# Build settings
markdown: kramdown
theme: minima
